CREATE TABLE OAUTH_AUTHORIZATION
(
    ID                            VARCHAR(255) NOT NULL,
    REGISTERED_CLIENT_ID          VARCHAR(255) NOT NULL,
    PRINCIPAL_NAME                VARCHAR(255) NOT NULL,
    AUTHORIZATION_GRANT_TYPE      VARCHAR(255) NOT NULL,
    -- 可选授权范围 的单词，一般不会太多
    AUTHORIZED_SCOPES             VARCHAR(512) NULL,
    ATTRIBUTES                    CLOB          DEFAULT NULL,
    STATE                         VARCHAR(500)  DEFAULT NULL,
    -- 不放东西 固定128
    AUTHORIZATION_CODE_VALUE      VARCHAR(255)  DEFAULT NULL,
    AUTHORIZATION_CODE_ISSUED_AT  TIMESTAMP     DEFAULT NULL,
    AUTHORIZATION_CODE_EXPIRES_AT TIMESTAMP     DEFAULT NULL,
    -- 不放东西基本不会超过 100
    AUTHORIZATION_CODE_METADATA   VARCHAR(255)  DEFAULT NULL,
    -- 放置约 30 个属性 约两千多
    ACCESS_TOKEN_VALUE            VARCHAR(3000) DEFAULT NULL,
    ACCESS_TOKEN_ISSUED_AT        TIMESTAMP     DEFAULT NULL,
    ACCESS_TOKEN_EXPIRES_AT       TIMESTAMP     DEFAULT NULL,
    ACCESS_TOKEN_METADATA         VARCHAR(2000) DEFAULT NULL,
    ACCESS_TOKEN_TYPE             VARCHAR(255)  DEFAULT NULL,
    ACCESS_TOKEN_SCOPES           VARCHAR(512)  DEFAULT NULL,
    -- 不放东西 固定128
    REFRESH_TOKEN_VALUE           VARCHAR(255)  DEFAULT NULL,
    REFRESH_TOKEN_ISSUED_AT       TIMESTAMP     DEFAULT NULL,
    REFRESH_TOKEN_EXPIRES_AT      TIMESTAMP     DEFAULT NULL,
    -- 不放东西基本不会超过 100
    REFRESH_TOKEN_METADATA        VARCHAR(255)  DEFAULT NULL,
    -- 放置20个属性 约两千多
    OIDC_ID_TOKEN_VALUE           VARCHAR(3000) DEFAULT NULL,
    OIDC_ID_TOKEN_ISSUED_AT       TIMESTAMP     DEFAULT NULL,
    OIDC_ID_TOKEN_EXPIRES_AT      TIMESTAMP     DEFAULT NULL,
    -- 下面这俩，放置20个属性，长度在 一千两三百左右
    OIDC_ID_TOKEN_METADATA        VARCHAR(2000) DEFAULT NULL,
    OIDC_ID_TOKEN_CLAIMS          VARCHAR(2000) DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE OAUTH_AUTHORIZATION_CONSENT
(
    REGISTERED_CLIENT_ID VARCHAR(255)  NOT NULL,
    PRINCIPAL_NAME       VARCHAR(255)  NOT NULL,
    AUTHORITIES          VARCHAR(1000) NOT NULL,
    PRIMARY KEY (REGISTERED_CLIENT_ID, PRINCIPAL_NAME)
);

CREATE TABLE OAUTH_CLIENT
(
    ID                            VARCHAR(255)                            NOT NULL,
    CLIENT_ID                     VARCHAR(255)                            NOT NULL,
    CLIENT_ID_ISSUED_AT           TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLIENT_SECRET                 VARCHAR(255)  DEFAULT NULL,
    CLIENT_SECRET_EXPIRES_AT      TIMESTAMP     DEFAULT NULL,
    CLIENT_NAME                   VARCHAR(255)                            NOT NULL,
    CLIENT_AUTHENTICATION_METHODS VARCHAR(1000)                           NOT NULL,
    AUTHORIZATION_GRANT_TYPES     VARCHAR(1000)                           NOT NULL,
    REDIRECT_URIS                 VARCHAR(1000) DEFAULT NULL,
    SCOPES                        VARCHAR(1000)                           NOT NULL,
    CLIENT_SETTINGS               VARCHAR(2000)                           NOT NULL,
    TOKEN_SETTINGS                VARCHAR(2000)                           NOT NULL,
    PRIMARY KEY (ID)
);